let
    Источник = Folder.Contents("\\mbn01fs03.becon.local\fileshare\mbn\подразделения\ДПЖ\37. Мероприятия ДПЖ"),
    // Выбирает папку с файлами для текущего года
    // Есть проверка на существование папки текущего года
    #"Выбор папки тек.года" = Table.SelectRows(Источник, each Text.Contains([Name], if
                                                                Table.RowCount(Table.FindText(Источник, Text.From(Date.Year(DateTime.LocalNow())))) > 0 then Text.From(Date.Year(DateTime.LocalNow()))
                                                                else Text.From(Date.Year(Date.AddYears(DateTime.LocalNow(), -1))))),
    // Выбор нужного файла с планом
    #"Выбор файла ПМ" = Table.SelectRows(#"Выбор папки тек.года"{0}[Content], each [Extension] = ".xlsm" and (not Text.Contains([Name], "~$")) and Text.Contains([Name], "ДПЖ") and (not Text.Contains([Name], "копия", Comparer.OrdinalIgnoreCase))),
    // Добавление признака предприятия + Развертка контента
    Признак_Предприятия = Table.ExpandTableColumn(
                                                Table.SelectColumns(
                                                                    Table.AddColumn(
                                                                                    Table.AddColumn(
                                                                                                    #"Выбор файла ПМ", "Table", each Excel.Workbook([Content])),
                                                                                    "Предприятие", each "РусАгро"), 
                                                                    {"Предприятие", "Table"}),
                                                "Table", {"Name", "Data"}),
    // Выбор листа в файле плана мероприятий
    #"Выбор листа плана" = Table.SelectColumns(Table.SelectRows(Признак_Предприятия, each Text.Contains([Name], "БП_"&#"Выбор папки тек.года"{0}[Name])), {"Предприятие", "Data"}),
    #"Развернутый элемент Data" = Table.ExpandTableColumn(#"Выбор листа плана", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63", "Column64", "Column65", "Column66", "Column67", "Column68", "Column69", "Column70", "Column71", "Column72", "Column73", "Column74", "Column75", "Column76", "Column77", "Column78", "Column79", "Column80", "Column81", "Column82", "Column83", "Column84", "Column85", "Column86", "Column87", "Column88", "Column89", "Column90", "Column91", "Column92", "Column93", "Column94", "Column95", "Column96", "Column97", "Column98", "Column99", "Column100", "Column101", "Column102", "Column103", "Column104", "Column105", "Column106", "Column107", "Column108", "Column109", "Column110", "Column111", "Column112", "Column113", "Column114", "Column115", "Column116", "Column117", "Column118", "Column119", "Column120", "Column121", "Column122", "Column123", "Column124", "Column125", "Column126", "Column127", "Column128", "Column129", "Column130", "Column131", "Column132", "Column133", "Column134", "Column135", "Column136", "Column137", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253", "Column254", "Column255", "Column256", "Column257", "Column258", "Column259", "Column260", "Column261", "Column262", "Column263", "Column264", "Column265", "Column266", "Column267", "Column268", "Column269"}, {"Data.Column1", "Data.Column2", "Data.Column3", "Data.Column4", "Data.Column5", "Data.Column6", "Data.Column7", "Data.Column8", "Data.Column9", "Data.Column10", "Data.Column11", "Data.Column12", "Data.Column13", "Data.Column14", "Data.Column15", "Data.Column16", "Data.Column17", "Data.Column18", "Data.Column19", "Data.Column20", "Data.Column21", "Data.Column22", "Data.Column23", "Data.Column24", "Data.Column25", "Data.Column26", "Data.Column27", "Data.Column28", "Data.Column29", "Data.Column30", "Data.Column31", "Data.Column32", "Data.Column33", "Data.Column34", "Data.Column35", "Data.Column36", "Data.Column37", "Data.Column38", "Data.Column39", "Data.Column40", "Data.Column41", "Data.Column42", "Data.Column43", "Data.Column44", "Data.Column45", "Data.Column46", "Data.Column47", "Data.Column48", "Data.Column49", "Data.Column50", "Data.Column51", "Data.Column52", "Data.Column53", "Data.Column54", "Data.Column55", "Data.Column56", "Data.Column57", "Data.Column58", "Data.Column59", "Data.Column60", "Data.Column61", "Data.Column62", "Data.Column63", "Data.Column64", "Data.Column65", "Data.Column66", "Data.Column67", "Data.Column68", "Data.Column69", "Data.Column70", "Data.Column71", "Data.Column72", "Data.Column73", "Data.Column74", "Data.Column75", "Data.Column76", "Data.Column77", "Data.Column78", "Data.Column79", "Data.Column80", "Data.Column81", "Data.Column82", "Data.Column83", "Data.Column84", "Data.Column85", "Data.Column86", "Data.Column87", "Data.Column88", "Data.Column89", "Data.Column90", "Data.Column91", "Data.Column92", "Data.Column93", "Data.Column94", "Data.Column95", "Data.Column96", "Data.Column97", "Data.Column98", "Data.Column99", "Data.Column100", "Data.Column101", "Data.Column102", "Data.Column103", "Data.Column104", "Data.Column105", "Data.Column106", "Data.Column107", "Data.Column108", "Data.Column109", "Data.Column110", "Data.Column111", "Data.Column112", "Data.Column113", "Data.Column114", "Data.Column115", "Data.Column116", "Data.Column117", "Data.Column118", "Data.Column119", "Data.Column120", "Data.Column121", "Data.Column122", "Data.Column123", "Data.Column124", "Data.Column125", "Data.Column126", "Data.Column127", "Data.Column128", "Data.Column129", "Data.Column130", "Data.Column131", "Data.Column132", "Data.Column133", "Data.Column134", "Data.Column135", "Data.Column136", "Data.Column137", "Data.Column138", "Data.Column139", "Data.Column140", "Data.Column141", "Data.Column142", "Data.Column143", "Data.Column144", "Data.Column145", "Data.Column146", "Data.Column147", "Data.Column148", "Data.Column149", "Data.Column150", "Data.Column151", "Data.Column152", "Data.Column153", "Data.Column154", "Data.Column155", "Data.Column156", "Data.Column157", "Data.Column158", "Data.Column159", "Data.Column160", "Data.Column161", "Data.Column162", "Data.Column163", "Data.Column164", "Data.Column165", "Data.Column166", "Data.Column167", "Data.Column168", "Data.Column169", "Data.Column170", "Data.Column171", "Data.Column172", "Data.Column173", "Data.Column174", "Data.Column175", "Data.Column176", "Data.Column177", "Data.Column178", "Data.Column179", "Data.Column180", "Data.Column181", "Data.Column182", "Data.Column183", "Data.Column184", "Data.Column185", "Data.Column186", "Data.Column187", "Data.Column188", "Data.Column189", "Data.Column190", "Data.Column191", "Data.Column192", "Data.Column193", "Data.Column194", "Data.Column195", "Data.Column196", "Data.Column197", "Data.Column198", "Data.Column199", "Data.Column200", "Data.Column201", "Data.Column202", "Data.Column203", "Data.Column204", "Data.Column205", "Data.Column206", "Data.Column207", "Data.Column208", "Data.Column209", "Data.Column210", "Data.Column211", "Data.Column212", "Data.Column213", "Data.Column214", "Data.Column215", "Data.Column216", "Data.Column217", "Data.Column218", "Data.Column219", "Data.Column220", "Data.Column221", "Data.Column222", "Data.Column223", "Data.Column224", "Data.Column225", "Data.Column226", "Data.Column227", "Data.Column228", "Data.Column229", "Data.Column230", "Data.Column231", "Data.Column232", "Data.Column233", "Data.Column234", "Data.Column235", "Data.Column236", "Data.Column237", "Data.Column238", "Data.Column239", "Data.Column240", "Data.Column241", "Data.Column242", "Data.Column243", "Data.Column244", "Data.Column245", "Data.Column246", "Data.Column247", "Data.Column248", "Data.Column249", "Data.Column250", "Data.Column251", "Data.Column252", "Data.Column253", "Data.Column254", "Data.Column255", "Data.Column256", "Data.Column257", "Data.Column258", "Data.Column259", "Data.Column260", "Data.Column261", "Data.Column262", "Data.Column263", "Data.Column264", "Data.Column265", "Data.Column266", "Data.Column267", "Data.Column268", "Data.Column269"}),
    #"Таблица плана" = Table.Skip(Table.PromoteHeaders(Table.Skip(#"Развернутый элемент Data",4)), 1),
    #"Переименованные столбцы" = Table.RenameColumns(#"Таблица плана",{{"Column17", "Проект"}, {"Column21", "Название шага"}, {"РусАгро", "Предприятие"}}),
    #"Другие удаленные столбцы" = Table.SelectColumns(#"Переименованные столбцы",{"Предприятие", "Блок", "Проект", "№ Шаг", "Название шага", "Начало", "Окончание", "Центр экспертизы", "Статус", "Фактическая дата выполнения", "Комментарий", "Карантин (СК Прогресс)", "ТР Дружба", "ТР Булановский", "ТР Маяк", "ТР Александровский", "ТР Ютановский", "ТР Шидловский", "ТР Прогресс", "ЦВРС Стрелица 7200", "ЦД Дубовской", "ЦД Садовый", "ЦД Желобок", "ЦД Гаевка", "ЦД Хуторской", "ЦД Новый", "ЦД Белый Колодезь", "ЦО Тюринский", "ЦО Осиновая роща", "ЦО Попова пасека", "ЦО Воронкино", "ЦО Шапкино", "ЦО Сиротино", "ЦО Журбинка", "ЦО Первомайский", "ЦО Становой", "ЦО Малиновский", "ЦО Екатериновский", "ЦО Вилочки 12000 голов", "Хрячник", "СК Сухосолотино", "СК Верхопенье", "СК Новоселовский", "СК Калиновский", "ЦПС Покровский", "ТР Яблоновский", "ЦО Яблоновский", "Племферма", "Дубки-1", "Дубки-2", "Ленинский-1", "Степное-1", "Степное-2", "Ленинский-2", "ЦПС", "Карантин (Натальевский)", "ПФ Натальевская", "ТР Бурнакский", "ТР Артемовский", "ТР Липовский", "ЦО Вязовский", "ЦО Савальский", "ЦО Еланьский", "ЦО Дубовский", "ЦО Питимский", "ЦО Александровский", "ЦПС 1", "ПФ Осиновская", "ТР Измайловский", "ТР Саюкинский", "ТР Марьевский", "ТР Беляевский", "ЦО Тикинский", "ЦО Новопавловский", "ЦО Ножкино", "ЦО Дубошино", "ЦО Ерофеевский", "ЦО Бахаревский", "ЦО Садовый", "ЦО Понзарьский", "ЦПС 2", "ТР Саюкинский 2", "ТР Марьевский 2", "ТР Липовский 2", "ТР Измайловский 2", "ЦО Ножкино 2", "ЦО Дубошино 2", "ЦО Ерофеевский 2", "ЦО Бахаревский 2", "ЦО Питимский 3", "ЦО Питимский 2", "ЦО Измайловский 3", "ЦПС 3"}),
    #"Замененное значение" = Table.ReplaceValue(#"Другие удаленные столбцы",null,"Основное мероприятие",Replacer.ReplaceValue,{"Название шага"}),
    #"Замененное значение1" = Table.ReplaceValue(#"Замененное значение","х","x",Replacer.ReplaceText,{"Карантин (СК Прогресс)", "ТР Дружба", "ТР Булановский", "ТР Маяк", "ТР Александровский", "ТР Ютановский", "ТР Шидловский", "ТР Прогресс", "ЦВРС Стрелица 7200", "ЦД Дубовской", "ЦД Садовый", "ЦД Желобок", "ЦД Гаевка", "ЦД Хуторской", "ЦД Новый", "ЦД Белый Колодезь", "ЦО Тюринский", "ЦО Осиновая роща", "ЦО Попова пасека", "ЦО Воронкино", "ЦО Шапкино", "ЦО Сиротино", "ЦО Журбинка", "ЦО Первомайский", "ЦО Становой", "ЦО Малиновский", "ЦО Екатериновский", "ЦО Вилочки 12000 голов", "Хрячник", "СК Сухосолотино", "СК Верхопенье", "СК Новоселовский", "СК Калиновский", "ЦПС Покровский", "ТР Яблоновский", "ЦО Яблоновский", "Племферма", "Дубки-1", "Дубки-2", "Ленинский-1", "Степное-1", "Степное-2", "Ленинский-2", "ЦПС", "Карантин (Натальевский)", "ПФ Натальевская", "ТР Бурнакский", "ТР Артемовский", "ТР Липовский", "ЦО Вязовский", "ЦО Савальский", "ЦО Еланьский", "ЦО Дубовский", "ЦО Питимский", "ЦО Александровский", "ЦПС 1", "ПФ Осиновская", "ТР Измайловский", "ТР Саюкинский", "ТР Марьевский", "ТР Беляевский", "ЦО Тикинский", "ЦО Новопавловский", "ЦО Ножкино", "ЦО Дубошино", "ЦО Ерофеевский", "ЦО Бахаревский", "ЦО Садовый", "ЦО Понзарьский", "ЦПС 2", "ТР Саюкинский 2", "ТР Марьевский 2", "ТР Липовский 2", "ТР Измайловский 2", "ЦО Ножкино 2", "ЦО Дубошино 2", "ЦО Ерофеевский 2", "ЦО Бахаревский 2", "ЦО Питимский 3", "ЦО Питимский 2", "ЦО Измайловский 3", "ЦПС 3"}),
    #"Замененное значение2" = Table.ReplaceValue(#"Замененное значение1",null,"N/A",Replacer.ReplaceValue,{"Карантин (СК Прогресс)", "ТР Дружба", "ТР Булановский", "ТР Маяк", "ТР Александровский", "ТР Ютановский", "ТР Шидловский", "ТР Прогресс", "ЦВРС Стрелица 7200", "ЦД Дубовской", "ЦД Садовый", "ЦД Желобок", "ЦД Гаевка", "ЦД Хуторской", "ЦД Новый", "ЦД Белый Колодезь", "ЦО Тюринский", "ЦО Осиновая роща", "ЦО Попова пасека", "ЦО Воронкино", "ЦО Шапкино", "ЦО Сиротино", "ЦО Журбинка", "ЦО Первомайский", "ЦО Становой", "ЦО Малиновский", "ЦО Екатериновский", "ЦО Вилочки 12000 голов", "Хрячник", "СК Сухосолотино", "СК Верхопенье", "СК Новоселовский", "СК Калиновский", "ЦПС Покровский", "ТР Яблоновский", "ЦО Яблоновский", "Племферма", "Дубки-1", "Дубки-2", "Ленинский-1", "Степное-1", "Степное-2", "Ленинский-2", "ЦПС", "Карантин (Натальевский)", "ПФ Натальевская", "ТР Бурнакский", "ТР Артемовский", "ТР Липовский", "ЦО Вязовский", "ЦО Савальский", "ЦО Еланьский", "ЦО Дубовский", "ЦО Питимский", "ЦО Александровский", "ЦПС 1", "ПФ Осиновская", "ТР Измайловский", "ТР Саюкинский", "ТР Марьевский", "ТР Беляевский", "ЦО Тикинский", "ЦО Новопавловский", "ЦО Ножкино", "ЦО Дубошино", "ЦО Ерофеевский", "ЦО Бахаревский", "ЦО Садовый", "ЦО Понзарьский", "ЦПС 2", "ТР Саюкинский 2", "ТР Марьевский 2", "ТР Липовский 2", "ТР Измайловский 2", "ЦО Ножкино 2", "ЦО Дубошино 2", "ЦО Ерофеевский 2", "ЦО Бахаревский 2", "ЦО Питимский 3", "ЦО Питимский 2", "ЦО Измайловский 3", "ЦПС 3"}),
    #"Замененное значение3" = Table.ReplaceValue(#"Замененное значение2","","N/A",Replacer.ReplaceValue,{"Карантин (СК Прогресс)", "ТР Дружба", "ТР Булановский", "ТР Маяк", "ТР Александровский", "ТР Ютановский", "ТР Шидловский", "ТР Прогресс", "ЦВРС Стрелица 7200", "ЦД Дубовской", "ЦД Садовый", "ЦД Желобок", "ЦД Гаевка", "ЦД Хуторской", "ЦД Новый", "ЦД Белый Колодезь", "ЦО Тюринский", "ЦО Осиновая роща", "ЦО Попова пасека", "ЦО Воронкино", "ЦО Шапкино", "ЦО Сиротино", "ЦО Журбинка", "ЦО Первомайский", "ЦО Становой", "ЦО Малиновский", "ЦО Екатериновский", "ЦО Вилочки 12000 голов", "Хрячник", "СК Сухосолотино", "СК Верхопенье", "СК Новоселовский", "СК Калиновский", "ЦПС Покровский", "ТР Яблоновский", "ЦО Яблоновский", "Племферма", "Дубки-1", "Дубки-2", "Ленинский-1", "Степное-1", "Степное-2", "Ленинский-2", "ЦПС", "Карантин (Натальевский)", "ПФ Натальевская", "ТР Бурнакский", "ТР Артемовский", "ТР Липовский", "ЦО Вязовский", "ЦО Савальский", "ЦО Еланьский", "ЦО Дубовский", "ЦО Питимский", "ЦО Александровский", "ЦПС 1", "ПФ Осиновская", "ТР Измайловский", "ТР Саюкинский", "ТР Марьевский", "ТР Беляевский", "ЦО Тикинский", "ЦО Новопавловский", "ЦО Ножкино", "ЦО Дубошино", "ЦО Ерофеевский", "ЦО Бахаревский", "ЦО Садовый", "ЦО Понзарьский", "ЦПС 2", "ТР Саюкинский 2", "ТР Марьевский 2", "ТР Липовский 2", "ТР Измайловский 2", "ЦО Ножкино 2", "ЦО Дубошино 2", "ЦО Ерофеевский 2", "ЦО Бахаревский 2", "ЦО Питимский 3", "ЦО Питимский 2", "ЦО Измайловский 3", "ЦПС 3"}),
    #"Замененное значение4" = Table.ReplaceValue(#"Замененное значение3","у","y",Replacer.ReplaceText,{"Карантин (СК Прогресс)", "ТР Дружба", "ТР Булановский", "ТР Маяк", "ТР Александровский", "ТР Ютановский", "ТР Шидловский", "ТР Прогресс", "ЦВРС Стрелица 7200", "ЦД Дубовской", "ЦД Садовый", "ЦД Желобок", "ЦД Гаевка", "ЦД Хуторской", "ЦД Новый", "ЦД Белый Колодезь", "ЦО Тюринский", "ЦО Осиновая роща", "ЦО Попова пасека", "ЦО Воронкино", "ЦО Шапкино", "ЦО Сиротино", "ЦО Журбинка", "ЦО Первомайский", "ЦО Становой", "ЦО Малиновский", "ЦО Екатериновский", "ЦО Вилочки 12000 голов", "Хрячник", "СК Сухосолотино", "СК Верхопенье", "СК Новоселовский", "СК Калиновский", "ЦПС Покровский", "ТР Яблоновский", "ЦО Яблоновский", "Племферма", "Дубки-1", "Дубки-2", "Ленинский-1", "Степное-1", "Степное-2", "Ленинский-2", "ЦПС", "Карантин (Натальевский)", "ПФ Натальевская", "ТР Бурнакский", "ТР Артемовский", "ТР Липовский", "ЦО Вязовский", "ЦО Савальский", "ЦО Еланьский", "ЦО Дубовский", "ЦО Питимский", "ЦО Александровский", "ЦПС 1", "ПФ Осиновская", "ТР Измайловский", "ТР Саюкинский", "ТР Марьевский", "ТР Беляевский", "ЦО Тикинский", "ЦО Новопавловский", "ЦО Ножкино", "ЦО Дубошино", "ЦО Ерофеевский", "ЦО Бахаревский", "ЦО Садовый", "ЦО Понзарьский", "ЦПС 2", "ТР Саюкинский 2", "ТР Марьевский 2", "ТР Липовский 2", "ТР Измайловский 2", "ЦО Ножкино 2", "ЦО Дубошино 2", "ЦО Ерофеевский 2", "ЦО Бахаревский 2", "ЦО Питимский 3", "ЦО Питимский 2", "ЦО Измайловский 3", "ЦПС 3"}),
    #"Несвернутые столбцы" = Table.UnpivotOtherColumns(#"Замененное значение4", {"Предприятие", "№ Шаг", "Блок", "Проект", "Название шага", "Начало", "Окончание", "Центр экспертизы", "Статус", "Фактическая дата выполнения", "Комментарий"}, "Атрибут", "Значение"),
    #"Переименованные столбцы1" = Table.RenameColumns(#"Несвернутые столбцы",{{"Атрибут", "Площадка"}, {"Значение", "Признак участия"}}),
    #"Срез по году" = Table.SelectRows(#"Переименованные столбцы1", each Date.Year([Окончание]) >= Date.Year(DateTime.LocalNow()))
in
    #"Срез по году"


let
    Источник = Table.Combine({#"План РусАгро", #"План АгроБелогорья"}),
    #"Замененное значение" = Table.ReplaceValue(Источник,"N/A",null,Replacer.ReplaceValue,{"Признак участия"}),
    #"Добавлен статус_BI" = Table.AddColumn(#"Замененное значение", "Статус_BI", each 
let
today = Date.From(DateTime.LocalNow())
in

if      [Статус] = "Выполнено" then "Выполнено"
else if [Статус] = "Отменено"  then "Отменено"
else if [Статус] = "Перенос 2027"  then "Перенос 2027"
else if [Статус] = "Не выполнено"  then "Просрочено"
else if [Статус] = "В обсуждении" then "В обсуждении"
else if [Статус] = "В процессе" then 
     if today > [Окончание] then "Просрочено"
     else "В процессе" // Потребуется корректировка в данном фрагменте с учетом простановки признака выполнения "Y"
else if [Статус] = null then
     if today > [Окончание] then "Просрочено"
     else if
        today > [Начало] then "Не начат в срок"
     else "Срок не наступил"
     else "Нужна проверка разработки"),
    #"Определение шаг/мероприятие" = Table.AddColumn(#"Добавлен статус_BI", "Мероприятие\Шаг", each if [Название шага] = "Основное мероприятие" then "Мероприятие" else "Шаг"),
    #"Измененный тип" = Table.TransformColumnTypes(#"Определение шаг/мероприятие",{{"Начало", type date}, {"Окончание", type date}, {"Фактическая дата выполнения", type date}})
in
    #"Измененный тип"





